version: "3.9"

services:
  catalog-db:
    image: postgres:15-alpine
    container_name: catalog-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
      - ./postgres/scripts/ddl.catalog.sql:/docker-entrypoint-initdb.d/01_catalog-ddl.sql
      - ./postgres/scripts/dml.catalog.sql:/docker-entrypoint-initdb.d/02_catalog-dml.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d catalog -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - catalog-net

  catalog-api:
    build: ./api
    container_name: catalog-api
    ports:
      - "5100:5100"
    volumes:
      - ./api:/app
    depends_on:
      - catalog-db
    networks:
      - catalog-net

networks:
  catalog-net:
    name: catalog-net
